---
dist: focal
language: ruby
# language: minimal
group: dev
arch: arm64

install: skip

script:
- cat /etc/os-release
- uname -a
- uname -r
- systemd-analyze time
- systemd-analyze blame
- echo "The CITAS Protocol PoC"

# - chmod u+x sc.sh 
# you want the most verbosity when it comes to the CITAS protocol, the whole point of following this is to have a scope of where you started, and where you want it to end successfully
